/* SPDX-License-Identifier: MIT */
/* Copyright (c) 2026 jkontiokoski */

#include "example_signals.h"

#include <stddef.h>

const j1939_signal_t example_signals[EXAMPLE_SIGNAL_COUNT] = {
        [EXAMPLE_PUMP_SPEED] = {.spn = 520192U,
                                .pgn = EXAMPLE_PGN_PUMP_STATUS,
                                .start = J1939_SIGNAL_POS(1U, 1U),
                                .bits = 16U,
                                .type = J1939_SIGNAL_TYPE_CONTINUOUS,
                                .res_num = 1U,
                                .res_den = 8U,
                                .offset = 0,
                                .unit = "rpm",
                                .name = "Pump speed"},
        [EXAMPLE_OIL_TEMP] = {.spn = 520193U,
                              .pgn = EXAMPLE_PGN_PUMP_STATUS,
                              .start = J1939_SIGNAL_POS(3U, 1U),
                              .bits = 8U,
                              .type = J1939_SIGNAL_TYPE_CONTINUOUS,
                              .res_num = 1U,
                              .res_den = 1U,
                              .offset = -40,
                              .unit = "degC",
                              .name = "Oil temperature"},
        [EXAMPLE_SUPPLY_PRESSURE] = {.spn = 520194U,
                                     .pgn = EXAMPLE_PGN_PUMP_STATUS,
                                     .start = J1939_SIGNAL_POS(4U, 1U),
                                     .bits = 16U,
                                     .type = J1939_SIGNAL_TYPE_CONTINUOUS,
                                     .res_num = 125U,
                                     .res_den = 16U,
                                     .offset = 0,
                                     .unit = "mbar",
                                     .name = "Supply pressure"},
        [EXAMPLE_PUMP_ENABLED] = {.spn = 520195U,
                                  .pgn = EXAMPLE_PGN_PUMP_STATUS,
                                  .start = J1939_SIGNAL_POS(6U, 1U),
                                  .bits = 2U,
                                  .type = J1939_SIGNAL_TYPE_DISCRETE,
                                  .res_num = 1U,
                                  .res_den = 1U,
                                  .offset = 0,
                                  .unit = NULL,
                                  .name = "Pump enabled"},
        [EXAMPLE_FILTER_CLOGGED] = {.spn = 520196U,
                                    .pgn = EXAMPLE_PGN_PUMP_STATUS,
                                    .start = J1939_SIGNAL_POS(6U, 3U),
                                    .bits = 2U,
                                    .type = J1939_SIGNAL_TYPE_DISCRETE,
                                    .res_num = 1U,
                                    .res_den = 1U,
                                    .offset = 0,
                                    .unit = NULL,
                                    .name = "Filter clogged"},
        [EXAMPLE_PUMP_MODE] = {.spn = 520197U,
                               .pgn = EXAMPLE_PGN_PUMP_STATUS,
                               .start = J1939_SIGNAL_POS(6U, 5U),
                               .bits = 4U,
                               .type = J1939_SIGNAL_TYPE_PLAIN,
                               .res_num = 1U,
                               .res_den = 1U,
                               .offset = 0,
                               .unit = NULL,
                               .name = "Pump mode"},
        [EXAMPLE_VALVE_POSITION] = {.spn = 520198U,
                                    .pgn = EXAMPLE_PGN_PUMP_STATUS,
                                    .start = J1939_SIGNAL_POS(7U, 1U),
                                    .bits = 10U,
                                    .type = J1939_SIGNAL_TYPE_PLAIN,
                                    .res_num = 1U,
                                    .res_den = 10U,
                                    .offset = 0,
                                    .unit = "%",
                                    .name = "Valve position"},
        [EXAMPLE_OPERATING_TIME] = {.spn = 520199U,
                                    .pgn = EXAMPLE_PGN_PUMP_COUNTERS,
                                    .start = J1939_SIGNAL_POS(1U, 1U),
                                    .bits = 32U,
                                    .type = J1939_SIGNAL_TYPE_CONTINUOUS,
                                    .res_num = 3U,
                                    .res_den = 1U,
                                    .offset = 0,
                                    .unit = "min",
                                    .name = "Operating time"},
        [EXAMPLE_TILT_ANGLE] = {.spn = 520200U,
                                .pgn = EXAMPLE_PGN_PUMP_COUNTERS,
                                .start = J1939_SIGNAL_POS(5U, 1U),
                                .bits = 16U,
                                .type = J1939_SIGNAL_TYPE_CONTINUOUS,
                                .res_num = 125U,
                                .res_den = 16U,
                                .offset = -250000,
                                .unit = "mdeg",
                                .name = "Tilt angle"},
        [EXAMPLE_FAULT_COUNT] = {.spn = 520201U,
                                 .pgn = EXAMPLE_PGN_PUMP_COUNTERS,
                                 .start = J1939_SIGNAL_POS(7U, 1U),
                                 .bits = 8U,
                                 .type = J1939_SIGNAL_TYPE_CONTINUOUS,
                                 .res_num = 1U,
                                 .res_den = 1U,
                                 .offset = 0,
                                 .unit = "count",
                                 .name = "Fault count"},
};
