/* SPDX-License-Identifier: MIT */
/* Copyright (c) 2026 jkontiokoski */

#include "j1939/j1939_tp.h"

#include <stddef.h>
#include <string.h>

#include "j1939/j1939_addr.h"
#include "j1939/j1939_id.h"
#include "j1939_addr_priv.h"
#include "j1939_ring_priv.h"
#include "j1939_rxobj_priv.h"
#include "j1939_stack_priv.h"
#include "j1939_tp_priv.h"

#define FRAME_LEN   8U    /* TP.CM and TP.DT frames always carry 8 bytes. */
#define PACKET_DATA 7U    /* Payload bytes per TP.DT packet. */
#define PAD         0xFFU /* Reserved bytes, unused packet bytes, "no limit". */
#define BYTE_MASK   0xFFU
#define BYTE_SHIFT  8U
#define TP_PRIO     7U /* Priority of the frames a responder sends, and of aborts. */

/* TP.CM control bytes. */
#define CTRL_RTS   0x10U
#define CTRL_CTS   0x11U
#define CTRL_EOMA  0x13U
#define CTRL_BAM   0x20U
#define CTRL_ABORT 0xFFU

/* TP.CM byte positions. */
#define CM_CTRL    0U
#define CM_LEN_LO  1U
#define CM_LEN_HI  2U
#define CM_PACKETS 3U
#define CM_LIMIT   4U
#define CM_PGN     5U
#define CTS_COUNT  1U
#define CTS_NEXT   2U

/* Accepted announcement (no abort reason). */
#define REASON_NONE 0U

/* Buffer states. */
#define BUF_FREE      0U
#define BUF_SESSION   1U
#define BUF_DELIVERED 2U

#define BAM_GAP_US   ((uint32_t)J1939_CFG_TP_BAM_GAP_US)
#define BAM_STALL_US (BAM_GAP_US + J1939_TP_TR_US)
#define SESSIONS     ((uint8_t)J1939_CFG_TP_SESSIONS)
#define BUF_SIZE     ((uint16_t)J1939_CFG_TP_BUF_SIZE)

static uint32_t cm_pgn_get(const uint8_t *data) {
	return (uint32_t)data[0] | ((uint32_t)data[1] << BYTE_SHIFT) |
	       ((uint32_t)data[2] << (2U * BYTE_SHIFT));
}

static uint16_t packets_for(uint16_t len) {
	return (uint16_t)((len + (PACKET_DATA - 1U)) / PACKET_DATA);
}

static void cm_build(uint8_t *f, uint8_t ctrl, uint8_t b1, uint8_t b2, uint8_t b3, uint8_t b4,
                     uint32_t pgn) {
	f[CM_CTRL] = ctrl;
	f[1] = b1;
	f[2] = b2;
	f[3] = b3;
	f[4] = b4;
	f[CM_PGN] = (uint8_t)(pgn & BYTE_MASK);
	f[CM_PGN + 1U] = (uint8_t)((pgn >> BYTE_SHIFT) & BYTE_MASK);
	f[CM_PGN + 2U] = (uint8_t)((pgn >> (2U * BYTE_SHIFT)) & BYTE_MASK);
}

/* Announcement (RTS, BAM, EndOfMsgAck) carrying the message size. */
static void cm_build_size(uint8_t *f, uint8_t ctrl, const j1939_tp_session_t *se) {
	cm_build(f, ctrl, (uint8_t)(se->len & BYTE_MASK), (uint8_t)(se->len >> BYTE_SHIFT),
	         (uint8_t)se->packets, PAD, se->pgn);
}

static bool tp_frame_send(j1939_t *s, uint8_t prio, uint32_t pgn, uint8_t sa, uint8_t da,
                          const uint8_t *f) {
	uint32_t id = 0U;
	j1939_ret_t ret = j1939_id_build(prio, pgn, da, sa, &id);

	if (ret == J1939_RET_OK) {
		ret = j1939_stack_tx(s, id, f, (uint8_t)FRAME_LEN);
	}
	return ret == J1939_RET_OK;
}

/* Sends a TP.CM frame generated by the stack; a full tx queue drops and counts it. */
static void tp_ctrl_send(j1939_t *s, uint8_t sa, uint8_t da, const uint8_t *f) {
	if (!tp_frame_send(s, TP_PRIO, J1939_PGN_TP_CM, sa, da, f)) {
		s->stats.tx_overflow++;
	}
}

static void tp_abort_send(j1939_t *s, uint8_t sa, uint8_t da, uint8_t reason, uint32_t pgn) {
	uint8_t f[FRAME_LEN];

	cm_build(f, CTRL_ABORT, reason, PAD, PAD, PAD, pgn);
	tp_ctrl_send(s, sa, da, f);
}

static void tp_timer_start(j1939_tp_session_t *se, uint32_t timeout_us, bool fresh) {
	se->timer_us = 0U;
	se->timeout_us = timeout_us;
	se->fresh = fresh;
}

static bool tp_timer_expired(const j1939_tp_session_t *se) {
	return se->timer_us >= se->timeout_us;
}

/* A delivered buffer is held while its message slot is unreleased and still refers to it. */
static bool tp_buf_held(j1939_t *s, const j1939_tp_buf_t *buf) {
	return j1939_ring_holds(&s->msgs.ring, buf->slot) && (s->msgs.buf[buf->slot].tp_buf == buf);
}

static j1939_tp_buf_t *tp_buf_alloc(j1939_t *s, j1939_tp_buf_t *pool, uint16_t len) {
	j1939_tp_buf_t *found = NULL;
	uint16_t i;

	for (i = 0U; (found == NULL) && (i < len); i++) {
		j1939_tp_buf_t *buf = &pool[i];

		if ((buf->state == BUF_DELIVERED) && !tp_buf_held(s, buf)) {
			buf->state = BUF_FREE;
		}
		if (buf->state == BUF_FREE) {
			found = buf;
		}
	}
	return found;
}

static j1939_tp_session_t *session_find(j1939_t *s, bool tx, uint8_t local, uint8_t remote) {
	j1939_tp_session_t *found = NULL;
	uint8_t i;

	for (i = 0U; (found == NULL) && (i < SESSIONS); i++) {
		j1939_tp_session_t *se = &s->tp.sessions[i];

		if ((se->state != J1939_TP_IDLE) && (se->tx == tx) && (se->local == local) &&
		    (se->remote == remote)) {
			found = se;
		}
	}
	return found;
}

/* Connection mode session between local and remote for pgn, or NULL. */
static j1939_tp_session_t *session_match(j1939_t *s, bool tx, uint8_t local, uint8_t remote,
                                         uint32_t pgn) {
	j1939_tp_session_t *se = session_find(s, tx, local, remote);

	if ((se != NULL) && (se->pgn != pgn)) {
		se = NULL;
	}
	return se;
}

/*
 * Reserves an unused session and a buffer from pool. Returns NULL and sets
 * reason to J1939_TP_ABORT_BUSY (no session) or J1939_TP_ABORT_RESOURCES
 * (no buffer) if either is missing.
 */
static j1939_tp_session_t *session_new(j1939_t *s, j1939_tp_buf_t *pool, uint16_t pool_len,
                                       uint8_t *reason) {
	j1939_tp_session_t *found = NULL;
	uint8_t i;

	*reason = J1939_TP_ABORT_BUSY;
	for (i = 0U; (found == NULL) && (i < SESSIONS); i++) {
		if (s->tp.sessions[i].state == J1939_TP_IDLE) {
			found = &s->tp.sessions[i];
		}
	}
	if (found != NULL) {
		j1939_tp_buf_t *buf = tp_buf_alloc(s, pool, pool_len);

		if (buf == NULL) {
			*reason = J1939_TP_ABORT_RESOURCES;
			found = NULL;
		} else {
			buf->state = BUF_SESSION;
			found->buf = buf;
			*reason = REASON_NONE;
		}
	}
	return found;
}

/* Sets the message and peer of a session returned by session_new(). */
static void session_open(j1939_tp_session_t *se, bool tx, uint8_t local, uint8_t remote,
                         const j1939_msg_t *msg) {
	se->tx = tx;
	se->local = local;
	se->remote = remote;
	se->pgn = msg->pgn;
	se->prio = msg->prio;
	se->len = msg->len;
	se->packets = packets_for(msg->len);
	se->next = 1U;
	se->last = 0U;
	se->limit = PAD;
	se->holds = 0U;
}

static void session_close(j1939_tp_session_t *se) {
	if (se->buf->state == BUF_SESSION) {
		se->buf->state = BUF_FREE;
	}
	se->buf = NULL;
	se->state = J1939_TP_IDLE;
}

/* Ends a session without its message, counting it. */
static void session_drop(j1939_t *s, j1939_tp_session_t *se) {
	if (se->tx) {
		s->stats.tp_tx_aborted++;
	} else {
		s->stats.tp_rx_aborted++;
	}
	session_close(se);
}

/* Ends a connection mode session with a Connection Abort to the peer. */
static void session_abort(j1939_t *s, j1939_tp_session_t *se, uint8_t reason) {
	tp_abort_send(s, se->local, se->remote, reason, se->pgn);
	session_drop(s, se);
}

/* Returns true if pgn goes to the application; Commanded Address may be for the stack only. */
static bool tp_for_app(const j1939_t *s, uint32_t pgn) {
	return j1939_stack_pgn_listed(s->rx_pgns, s->rx_pgns_len, pgn);
}

/* Returns true if the completed message of the session finds a message slot, or needs none. */
static bool tp_msg_slot_free(j1939_t *s, const j1939_tp_session_t *se) {
	uint16_t index;

	return !tp_for_app(s, se->pgn) || j1939_ring_head(&s->msgs.ring, &index);
}

/*
 * Hands the completed message to the application; its buffer stays reserved
 * until the pop. A receive object for it is updated whether or not a message
 * slot is free. A Commanded Address also goes to address management.
 */
static bool tp_deliver(j1939_t *s, j1939_tp_session_t *se) {
	uint16_t index;
	bool ok = true;

	j1939_rxobj_handle(s, se->pgn, se->remote, se->buf->data, se->len);
	if (!tp_for_app(s, se->pgn)) {
		/* For the stack only; the buffer is freed with the session. */
	} else if (j1939_ring_head(&s->msgs.ring, &index)) {
		j1939_msg_slot_t *slot = &s->msgs.buf[index];

		slot->msg.pgn = se->pgn;
		slot->msg.prio = se->prio;
		slot->msg.sa = se->remote;
		slot->msg.da = se->local;
		slot->msg.len = se->len;
		slot->msg.data = se->buf->data;
		slot->tp_buf = se->buf;
		se->buf->state = BUF_DELIVERED;
		se->buf->slot = index;
		(void)j1939_ring_push(&s->msgs.ring);
	} else {
		s->stats.rx_msg_overflow++;
		ok = false;
	}
	if (ok && (se->pgn == J1939_PGN_COMMANDED_ADDRESS)) {
		j1939_addr_command_handle(s, se->buf->data, se->len);
	}
	return ok;
}

/*
 * Checks an RTS or BAM. Returns REASON_NONE if the message can be received,
 * otherwise the abort reason. A message larger than the buffers is counted.
 */
static uint8_t announce_check(j1939_t *s, uint16_t len, uint8_t packets, uint32_t pgn, uint8_t sa) {
	uint8_t reason = REASON_NONE;

	if (len > J1939_TP_MSG_MAX) {
		reason = J1939_TP_ABORT_TOO_LARGE;
	} else if ((len < J1939_TP_MSG_MIN) || ((uint16_t)packets != packets_for(len))) {
		reason = J1939_TP_ABORT_OTHER;
	} else if (!tp_for_app(s, pgn) && !j1939_rxobj_wanted(s, pgn, sa) &&
	           !((pgn == J1939_PGN_COMMANDED_ADDRESS) && j1939_addr_command_accepted(s))) {
		reason = J1939_TP_ABORT_OTHER;
	} else if (len > BUF_SIZE) {
		s->stats.tp_rx_refused++;
		reason = J1939_TP_ABORT_RESOURCES;
	} else {
		/* Acceptable. */
	}
	return reason;
}

static void hold_send(j1939_t *s, const j1939_tp_session_t *se) {
	uint8_t f[FRAME_LEN];

	cm_build(f, CTRL_CTS, 0U, PAD, PAD, PAD, se->pgn);
	tp_ctrl_send(s, se->local, se->remote, f);
}

/*
 * Responder: requests the next packets. The CTS for the packets that
 * complete the message is held back (CTS with 0 packets) while all message
 * slots are in use.
 */
static void window_request(j1939_t *s, j1939_tp_session_t *se, bool fresh) {
	uint16_t n = (uint16_t)((se->packets - se->next) + 1U);

	if (n > se->limit) {
		n = se->limit;
	}
	if ((((se->next + n) - 1U) == se->packets) && !tp_msg_slot_free(s, se)) {
		se->state = J1939_TP_RX_HOLD;
		se->holds = 1U;
		hold_send(s, se);
		tp_timer_start(se, J1939_TP_TH_US, fresh);
	} else {
		uint8_t f[FRAME_LEN];

		se->state = J1939_TP_RX_DATA;
		se->last = (uint16_t)((se->next + n) - 1U);
		cm_build(f, CTRL_CTS, (uint8_t)n, (uint8_t)se->next, PAD, PAD, se->pgn);
		tp_ctrl_send(s, se->local, se->remote, f);
		tp_timer_start(se, J1939_TP_T2_US, fresh);
	}
}

/* Opens a receive session; returns the reason if none could be opened. */
static uint8_t rx_open(j1939_t *s, uint32_t id, const uint8_t *d, uint8_t local,
                       j1939_tp_session_t **out) {
	j1939_msg_t msg;
	uint8_t reason;

	msg.len = (uint16_t)((uint16_t)d[CM_LEN_LO] | ((uint16_t)d[CM_LEN_HI] << BYTE_SHIFT));
	msg.pgn = cm_pgn_get(&d[CM_PGN]);
	msg.prio = j1939_id_prio_get(id);
	reason = announce_check(s, msg.len, d[CM_PACKETS], msg.pgn, j1939_id_sa_get(id));
	*out = NULL;
	if (reason == REASON_NONE) {
		*out = session_new(s, s->tp.rx_buf, s->tp.rx_buf_len, &reason);
		if (*out == NULL) {
			s->stats.tp_rx_refused++;
		} else {
			session_open(*out, false, local, j1939_id_sa_get(id), &msg);
		}
	}
	return reason;
}

static void rts_handle(j1939_t *s, uint32_t id, const uint8_t *d) {
	uint8_t own = j1939_id_da_get(id);
	uint8_t peer = j1939_id_sa_get(id);
	uint32_t pgn = cm_pgn_get(&d[CM_PGN]);
	j1939_tp_session_t *se = session_find(s, false, own, peer);
	uint8_t reason;

	if ((se != NULL) && (se->pgn != pgn)) {
		/* One connection per originator: the open one continues. */
		reason = J1939_TP_ABORT_BUSY;
	} else {
		if (se != NULL) {
			/* A repeated RTS for the same PGN replaces the open connection, without an
			 * abort. */
			session_drop(s, se);
		}
		reason = rx_open(s, id, d, own, &se);
		if (se != NULL) {
			/* A limit of 0 is invalid; one packet per CTS suits every originator. */
			se->limit = (d[CM_LIMIT] == 0U) ? 1U : d[CM_LIMIT];
			window_request(s, se, true);
		}
	}
	if (reason != REASON_NONE) {
		tp_abort_send(s, own, peer, reason, pgn);
	}
}

static void bam_handle(j1939_t *s, uint32_t id, const uint8_t *d) {
	j1939_tp_session_t *se = session_find(s, false, J1939_ADDR_GLOBAL, j1939_id_sa_get(id));

	if (se != NULL) {
		/* A sender runs one broadcast at a time: a new one replaces an unfinished one. */
		session_drop(s, se);
	}
	(void)rx_open(s, id, d, J1939_ADDR_GLOBAL, &se);
	if (se != NULL) {
		se->state = J1939_TP_RX_BAM;
		tp_timer_start(se, J1939_TP_T1_US, true);
	}
}

static void cts_handle(j1939_t *s, j1939_tp_session_t *se, const uint8_t *d) {
	uint16_t n = d[CTS_COUNT];
	uint16_t next = d[CTS_NEXT];

	switch (se->state) {
	case J1939_TP_TX_WAIT:
	case J1939_TP_TX_HOLD:
		if (n == 0U) {
			se->state = J1939_TP_TX_HOLD;
			tp_timer_start(se, J1939_TP_T4_US, true);
		} else if ((next == 0U) || (((next + n) - 1U) > se->packets)) {
			session_abort(s, se, J1939_TP_ABORT_OTHER);
		} else {
			se->state = J1939_TP_TX_DATA;
			se->next = next;
			se->last = (uint16_t)((next + n) - 1U);
			tp_timer_start(se, J1939_TP_TR_US, true);
		}
		break;
	case J1939_TP_TX_DATA:
		session_abort(s, se, J1939_TP_ABORT_CTS_IN_DATA);
		break;
	default:
		/* Not a connection mode originator. */
		break;
	}
}

static void abort_handle(j1939_t *s, uint8_t own, uint8_t peer, uint32_t pgn) {
	j1939_tp_session_t *se = session_match(s, true, own, peer, pgn);

	if (se != NULL) {
		session_drop(s, se);
	}
	se = session_match(s, false, own, peer, pgn);
	if (se != NULL) {
		session_drop(s, se);
	}
}

static void cm_handle(j1939_t *s, uint32_t id, const uint8_t *d) {
	uint8_t own = j1939_id_da_get(id);
	uint8_t peer = j1939_id_sa_get(id);
	uint32_t pgn = cm_pgn_get(&d[CM_PGN]);
	bool global = own == J1939_ADDR_GLOBAL;
	j1939_tp_session_t *se;

	switch (d[CM_CTRL]) {
	case CTRL_RTS:
		/* A responder answers only from a claimed address; else the originator times out.
		 */
		if (!global && j1939_addr_claimed(s, own)) {
			rts_handle(s, id, d);
		}
		break;
	case CTRL_CTS:
		se = session_match(s, true, own, peer, pgn);
		if (se != NULL) {
			cts_handle(s, se, d);
		}
		break;
	case CTRL_EOMA:
		se = session_match(s, true, own, peer, pgn);
		if (se != NULL) {
			session_close(se);
		}
		break;
	case CTRL_BAM:
		if (global) {
			bam_handle(s, id, d);
		}
		break;
	case CTRL_ABORT:
		abort_handle(s, own, peer, pgn);
		break;
	default:
		/* Reserved control byte. */
		break;
	}
}

static void packet_store(j1939_tp_session_t *se, const uint8_t *d) {
	uint16_t offset = (uint16_t)((se->next - 1U) * PACKET_DATA);
	uint16_t n = (uint16_t)(se->len - offset);

	if (n > PACKET_DATA) {
		n = PACKET_DATA;
	}
	(void)memcpy(&se->buf->data[offset], &d[1], n);
	se->next++;
}

static void rx_complete(j1939_t *s, j1939_tp_session_t *se) {
	if (tp_deliver(s, se)) {
		uint8_t f[FRAME_LEN];

		cm_build_size(f, CTRL_EOMA, se);
		tp_ctrl_send(s, se->local, se->remote, f);
		session_close(se);
	} else {
		session_abort(s, se, J1939_TP_ABORT_RESOURCES);
	}
}

static void dt_handle(j1939_t *s, uint32_t id, const uint8_t *d) {
	j1939_tp_session_t *se = session_find(s, false, j1939_id_da_get(id), j1939_id_sa_get(id));
	uint16_t seq = d[0];

	/* Packets already received are ignored. */
	if ((se != NULL) && (seq >= se->next)) {
		switch (se->state) {
		case J1939_TP_RX_BAM:
			if (seq > se->next) {
				/* Lost packet; a broadcast cannot be repeated. */
				session_drop(s, se);
			} else {
				packet_store(se, d);
				if (se->next <= se->packets) {
					tp_timer_start(se, J1939_TP_T1_US, true);
				} else if (tp_deliver(s, se)) {
					session_close(se);
				} else {
					session_drop(s, se);
				}
			}
			break;
		case J1939_TP_RX_DATA:
			if (seq > se->next) {
				session_abort(s, se, J1939_TP_ABORT_BAD_SEQ);
			} else {
				packet_store(se, d);
				if (se->next > se->packets) {
					rx_complete(s, se);
				} else if (se->next > se->last) {
					window_request(s, se, true);
				} else {
					tp_timer_start(se, J1939_TP_T1_US, true);
				}
			}
			break;
		case J1939_TP_RX_HOLD:
			session_abort(s, se, J1939_TP_ABORT_UNEXPECTED_DT);
			break;
		default:
			/* Not a receive session. */
			break;
		}
	}
}

static bool dt_send(j1939_t *s, const j1939_tp_session_t *se) {
	uint8_t f[FRAME_LEN];
	uint16_t offset = (uint16_t)((se->next - 1U) * PACKET_DATA);
	uint16_t n = (uint16_t)(se->len - offset);

	if (n > PACKET_DATA) {
		n = PACKET_DATA;
	}
	(void)memset(f, (int)PAD, sizeof(f));
	f[0] = (uint8_t)se->next;
	(void)memcpy(&f[1], &se->buf->data[offset], n);
	return tp_frame_send(s, se->prio, J1939_PGN_TP_DT, se->local, se->remote, f);
}

static void bam_tick(j1939_t *s, j1939_tp_session_t *se) {
	if (tp_timer_expired(se)) {
		if (dt_send(s, se)) {
			se->next++;
			if (se->next > se->packets) {
				session_close(se);
			} else {
				tp_timer_start(se, BAM_GAP_US, false);
			}
		} else if (se->timer_us >= BAM_STALL_US) {
			/* Receivers would have timed out; a broadcast has no abort. */
			session_drop(s, se);
		} else {
			/* Tx queue full: retry at the next call. */
		}
	}
}

/* Originator: sends the requested packets as far as the tx queue has room. */
static void data_tick(j1939_t *s, j1939_tp_session_t *se) {
	uint16_t n = (uint16_t)((se->last - se->next) + 1U);
	bool sent = true;
	bool progress = false;
	uint16_t i;

	for (i = 0U; sent && (i < n); i++) {
		sent = dt_send(s, se);
		if (sent) {
			se->next++;
			progress = true;
		}
	}
	if (se->next > se->last) {
		se->state = J1939_TP_TX_WAIT;
		tp_timer_start(se, J1939_TP_T3_US, false);
	} else if (progress) {
		tp_timer_start(se, J1939_TP_TR_US, false);
	} else if (tp_timer_expired(se)) {
		session_abort(s, se, J1939_TP_ABORT_TIMEOUT);
	} else {
		/* Tx queue full: retry at the next call. */
	}
}

static void hold_tick(j1939_t *s, j1939_tp_session_t *se) {
	if (tp_msg_slot_free(s, se)) {
		window_request(s, se, false);
	} else if (tp_timer_expired(se)) {
		if (se->holds >= J1939_TP_HOLD_MAX) {
			session_abort(s, se, J1939_TP_ABORT_RESOURCES);
		} else {
			se->holds++;
			hold_send(s, se);
			tp_timer_start(se, J1939_TP_TH_US, false);
		}
	} else {
		/* Keep holding. */
	}
}

static void session_tick(j1939_t *s, j1939_tp_session_t *se) {
	switch (se->state) {
	case J1939_TP_TX_BAM:
		bam_tick(s, se);
		break;
	case J1939_TP_TX_DATA:
		data_tick(s, se);
		break;
	case J1939_TP_TX_WAIT:
	case J1939_TP_TX_HOLD:
	case J1939_TP_RX_DATA:
		if (tp_timer_expired(se)) {
			session_abort(s, se, J1939_TP_ABORT_TIMEOUT);
		}
		break;
	case J1939_TP_RX_BAM:
		if (tp_timer_expired(se)) {
			session_drop(s, se);
		}
		break;
	case J1939_TP_RX_HOLD:
		hold_tick(s, se);
		break;
	default:
		/* Idle. */
		break;
	}
}

static void tp_pool_init(j1939_tp_buf_t *pool, uint16_t len) {
	uint16_t i;

	for (i = 0U; i < len; i++) {
		pool[i].state = BUF_FREE;
		pool[i].slot = 0U;
	}
}

bool j1939_tp_cfg_valid(const j1939_cfg_t *cfg) {
	return ((cfg->tp_tx_buf != NULL) || (cfg->tp_tx_buf_len == 0U)) &&
	       ((cfg->tp_rx_buf != NULL) || (cfg->tp_rx_buf_len == 0U));
}

void j1939_tp_init(j1939_t *s, const j1939_cfg_t *cfg) {
	/* Locals keep cppcheck's MISRA 11.8 check from treating the buffers as const. */
	j1939_tp_buf_t *tx_buf = cfg->tp_tx_buf;
	j1939_tp_buf_t *rx_buf = cfg->tp_rx_buf;
	uint8_t i;

	for (i = 0U; i < SESSIONS; i++) {
		s->tp.sessions[i].state = J1939_TP_IDLE;
		s->tp.sessions[i].buf = NULL;
	}
	s->tp.tx_buf = tx_buf;
	s->tp.tx_buf_len = cfg->tp_tx_buf_len;
	s->tp.rx_buf = rx_buf;
	s->tp.rx_buf_len = cfg->tp_rx_buf_len;
	tp_pool_init(tx_buf, cfg->tp_tx_buf_len);
	tp_pool_init(rx_buf, cfg->tp_rx_buf_len);
	s->stats.tp_tx_aborted = 0U;
	s->stats.tp_rx_aborted = 0U;
	s->stats.tp_rx_refused = 0U;
}

void j1939_tp_handle(j1939_t *s, uint32_t id, const uint8_t *data, uint8_t len) {
	/* TP frames are 8 bytes long and come from a valid source address. */
	if ((len == FRAME_LEN) && (j1939_id_sa_get(id) < J1939_ADDR_NULL)) {
		if (j1939_id_pgn_get(id) == J1939_PGN_TP_CM) {
			cm_handle(s, id, data);
		} else {
			dt_handle(s, id, data);
		}
	}
}

void j1939_tp_address_lost(j1939_t *s, uint8_t address) {
	uint8_t i;

	for (i = 0U; i < SESSIONS; i++) {
		j1939_tp_session_t *se = &s->tp.sessions[i];

		if ((se->state != J1939_TP_IDLE) && (se->local == address)) {
			session_drop(s, se);
		}
	}
}

void j1939_tp_process(j1939_t *s, uint32_t elapsed_us) {
	uint8_t i;

	for (i = 0U; i < SESSIONS; i++) {
		j1939_tp_session_t *se = &s->tp.sessions[i];

		if (se->state != J1939_TP_IDLE) {
			if (se->fresh) {
				/* Started during this call: count from the next one. */
				se->fresh = false;
			} else if (elapsed_us > (UINT32_MAX - se->timer_us)) {
				se->timer_us = UINT32_MAX;
			} else {
				se->timer_us += elapsed_us;
			}
			session_tick(s, se);
		}
	}
}

j1939_ret_t j1939_tp_send(j1939_t *s, uint8_t sa, const j1939_msg_t *msg) {
	j1939_ret_t ret = J1939_RET_ERR_ARG;
	/* The TP.CM frames carry the destination, so a PDU2 PGN may go to a single node. */
	uint8_t id_da = j1939_pgn_is_pdu1(msg->pgn) ? msg->da : J1939_ADDR_GLOBAL;
	uint8_t reason;
	uint32_t id;

	if ((msg->len > BUF_SIZE) ||
	    (j1939_id_build(msg->prio, msg->pgn, id_da, sa, &id) != J1939_RET_OK)) {
		/* Too long for a transmit buffer, or an invalid identifier. */
	} else if (session_find(s, true, sa, msg->da) != NULL) {
		ret = J1939_RET_ERR_BUSY;
	} else {
		j1939_tp_session_t *se = session_new(s, s->tp.tx_buf, s->tp.tx_buf_len, &reason);

		ret = J1939_RET_ERR_FULL;
		if (se != NULL) {
			bool bam = msg->da == J1939_ADDR_GLOBAL;
			uint8_t f[FRAME_LEN];

			session_open(se, true, sa, msg->da, msg);
			(void)memcpy(se->buf->data, msg->data, msg->len);
			cm_build_size(f, bam ? CTRL_BAM : CTRL_RTS, se);
			if (tp_frame_send(s, se->prio, J1939_PGN_TP_CM, sa, msg->da, f)) {
				se->state = bam ? J1939_TP_TX_BAM : J1939_TP_TX_WAIT;
				tp_timer_start(se, bam ? BAM_GAP_US : J1939_TP_T3_US, true);
				ret = J1939_RET_OK;
			} else {
				session_close(se);
			}
		}
	}
	return ret;
}
